version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bills
    volumes:
      - bills_pg_data:/bitnami/postgresql
    networks:
      - db

  app:
    build: .
    networks:
      - db
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - TOKENGENERATOR_CLIENT_ID="bd753592-cf9b-4d1a-96b9-cb8b2c01bd12"
      - TOKENGENERATOR_CLIENT_SECRET="4e8229fe-1131-439c-9846-799895a8be5b"
      - TOKENGENERATOR_HOSTNAME="vagas.builders"
      - TOKENGENERATOR_PATH="/api/builders/auth/tokens"
      - BILLINFO_HOSTNAME="vagas.builders"
      - BILLINFO_PATH="/api/builders/bill-payments/codes"
      - SECRET="desafio-tecnico"
      - PORT=3000
    command: "npm run start"

volumes:
  bills_pg_data:

networks:
  db:
    driver: bridge