version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:16.2.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bills
    volumes:
      - bills_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:7.2.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - bills_redis_data:/bitnami/redis/data

volumes:
  bills_pg_data:
  bills_redis_data:
